package dao;
// Generated 09-Nov-2017 08:46:16 by Hibernate Tools 5.2.6.Final

/**
 * Karywan generated by hbm2java
 */
public class Karywan implements java.io.Serializable {

	private String kode;
	private String nama;

	public Karywan() {
	}

	public Karywan(String kode, String nama) {
		this.kode = kode;
		this.nama = nama;
	}

	public String getKode() {
		return this.kode;
	}

	public void setKode(String kode) {
		this.kode = kode;
	}

	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

}
